Use ruamel.yaml for YAMLEditable
scheibler/khard pull request #302
Opened 2022-02-27 20:29 UTC by skowalak

replace the YAMLEditable.to_yaml() method with ruamel serialization.
migrate some yaml formatting to the helpers module.

2022-02-27 20:35 UTC, skowalak commented
This PR references (#276)
The entire `YAMLEditable.to_yaml()` function is rewritten to use `ruamel.yaml`

What I have not done (yet):
* Pretty printing still relies on `helpers.convert_to_yaml()`. I don't know if that level of indentation/alignment is possible with ruamel
* Values will be inserted in the standard template. I don't know if this breaks some workflows involving custom new user templates (#146).
* Helper tests still use `helpers.convert_to_yaml()`. I will add some tests for the new methods when I have some more time.

2022-02-27 21:36 UTC, lucc reviewed
I did a quick review of the helper code, just to give you an idea.  I will of course do another one at least when you remove the draft state.

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +        value = None
You do not need the local variable `value` (or rather overwrite the argument), you can just `return` directly.

Also see https://pheanex.github.io/pylint/

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +        defaults: Union[Dict[str, Any], List[str]] = None
Shouldn't that be a `Optional[Union[...]]` if it can be `None?

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +            return dict((key, None) for key in defaults)
You could use `dict.fromkeys` or at least  literal dict comprehension with `{ ... }` like below,  to keep your code style uniform.

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +    for t, nlist in sorted(data.items(), key=lambda k: k[0].lower()):
Why t and nlist and not key, value?  What do these names stand for, I don't understand them?

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +        address_fields = dict((key, None) for key in address_properties)
`dict.fromkeys`

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +        string = anniversary
You can `return` instead of assigning to `string`.

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +        address_dict[address_type] = (
outer parents are not needed.

2022-02-27 21:36 UTC, lucc commented on khard/helpers/__init__.py
> +def yaml_addresses(addresses: Optional[Dict[str, Any]],
Please add a doc comment.

2022-02-27 21:41 UTC, lucc commented
I think you need not bother with #146 because that issue is still in the discussion and planing phase. You can also leave the pretty printing alone as we just reuse the yaml conversion functions.  We do not officially claim that the output of the pretty printer is valid yaml.  We can thing about changing the pretty printer in another PR.

Please try to run the tests  and mypy (and maybe even pylint) locally because currently  travis integration is broken. (I need help from @scheibler to fix this.)

If you could also write a test for #276 (the string with an @) that would be great!

2022-02-28 21:23 UTC, skowalak commented
I have a little difficulty running the tests. When I run `python setup.py test` hangs at the line
```
test_contact_is_found_if_name_matches (test.test_command_line_interface.AddEmail) ... 
```
I have to interrupt the testing via `CTRL-C` because the process' memory usage grows beyond what I consider normal (10GiB). Is that correct? Could my changes have caused this behaviour, if incorrect?

2022-03-08 22:11 UTC, skowalak commented
Hi @lucc ,
after some troubleshooting the abovementioned issue, I tried running the tests on the `develop` branch and had the exact same problem (`tests.test_command_line_interface.AddEmail` hangs in an infinite loop consuming more and more memory). I even tried it on a different computer running a different OS.

So apparently my changes did not break the tests.

- [x] I ran mypy
- [x] I ran pylint
- [x] I wrote a test for #276 
- [ ] I successfully ran the tests

Is there anything more I need to do before this PR can be merged?

2022-03-08 23:13 UTC, lucc requested changes
You can skip the broken test like this:
```diff
diff --git a/test/test_command_line_interface.py b/test/test_command_line_interface.py
index cac683c..97b5ecf 100644
--- a/test/test_command_line_interface.py
+++ b/test/test_command_line_interface.py
@@ -480,6 +480,7 @@ class Merge(unittest.TestCase):
         self.assertEqual('contact2.vcf', second)


+@unittest.skip("reason for skipping")
 class AddEmail(unittest.TestCase):

     @TmpConfig(["contact1.vcf", "contact2.vcf"])
```

If I do that (*temporarily*!) the other tests all run fine.


I noticed that the birthday field and phone numbers as well as ZIP codes are now wrapped in quotes. Do you know if there is a way to only quote strings that are problematic (like the @ at the beginning)?

2022-03-08 23:13 UTC, lucc commented on khard/carddav_object.py
> -                    "Webpage", self.webpages, 0, 8, True)
I like this code reduction :)

2022-03-09 10:07 UTC, skowalak commented on khard/helpers/__init__.py
> +              ) -> Optional[Union[Sequence, List, str, Dict[str, Any],
I got a mypy error without the Sequence, meaning one of the properties of `YAMLEditable` that are used in `to_yaml` is of a Sequence type. I removed List though, thank you.

2022-03-09 11:10 UTC, skowalak commented
@lucc I implemented the changes you requested.
About the quoting, I am not entirely sure. I believe ZIP codes at least are quoted because they are strings consisting of numbers only and ruamel quotes them so they are not interpreted as `tag:yaml.org,2002:int`, which would for example remove leading zeroes. That does not apply to birthdays (as they include dashes), still they are quoted, when according to the yaml spec they do not have be quoted. I had a look over at [ruamels source code](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/emitter.py) but could not find out why.

So, if that is a big problem we could ofc ask Anthon van der Neut from ruamel if he knows if it is possible not to quote this.

2022-03-09 19:19 UTC, lucc approved these changes

2022-03-09 19:27 UTC, merged

2022-03-09 19:29 UTC, lucc commented
thank you  @skowalak !

We can leave the quoting for later. That is just aesthetics in my opinion.  The important thing is that yaml editing should be more robust now that #276 should be fixed.